config/routes.rb
Rails.application.routes.draw do
  resources :reviews
  get 'review/destroy'
  resources :orders
  get 'line_items/add'

  resources :line_items
  
  devise_for :users

  resources :categories
  resources :products
  

   root 'products#index'

end

app/models/category.rb
class Category < ActiveRecord::Base

validates_presence_of :name
validates_uniqueness_of :name
end

app/models/line_item.rb
class LineItem < ActiveRecord::Base
belongs_to :user
belongs_to :product

end

app/models/order.rb
class Order < ActiveRecord::Base
	belongs_to :user
	has_many :order_line_items
end

app/models/order_line_item.rb
class OrderLineItem < ActiveRecord::Base
belongs_to :order
belongs_to :product
end

app/models/product.rb
class Product < ActiveRecord::Base
	has_many :reviews
	belongs_to :category
	has_many :line_items
validates_presence_of :name
validates_uniqueness_of :name
end

app/models/review.rb
class Review < ActiveRecord::Base
	belongs_to :product
	belongs_to :user
end

app/models/student.rb
class Student < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
	has_many :reviews
	has_many :line_items
	has_many :orders

    
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  def check_is_admin
  	if  current_user.is_admin
  		return true
  	else
  		redirect_to "/categories", notice: "page not found"
  	end
end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
	before_action :authenticate_user!, except: [:index, :show]
	before_action :check_is_admin, except: [:index, :show] #check for url manipulation
  def index
    @categories=Category.all
  end
   def new
   	@category=Category.new
end
def create
	 @category=Category.new(params[:category].permit(:name))
	 if @category.save
	 	redirect_to "/categories",notice: "successfully created category"
	 else
	 	render action: "new"
end
end
def show
	  @category = Category.find(params[:id])
	  @products = Product.where('category_id = ?',params[:id])
end
def edit
	  @category = Category.find(params[:id])
	end

def update
	 @category = Category.find(params[:id])
	 if @category.update_attributes(params[:category].permit(:name))
	 	redirect_to @category, notice:"successfully updated the category"
	 else
	 	render action: "edit"
end
end
def destroy
	 @category=Category.find(params[:id])
	 @category.destroy
	 redirect_to "/categories",notice: "successfully deleted"
	end
end

app/controllers/line_items_controller.rb
class LineItemsController < ApplicationController
def index
	 @line_items = current_user.line_items
	end
	def destroy
		@line_item = LineItem.find(params[:id])
		@line_item.destroy
		redirect_to :back, notice: "successfully removed from cart"
	end
def add
	@product = Product.find(params[:product_id])
    line_item = LineItem.new
    line_item.product_id = @product.id 
    line_item.user_id = current_user.id 
    line_item.price = @product.price
    line_item.save
    
    redirect_to :back, notice: "added product to cart" 
end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
def index
	 @orders= current_user.orders
	end

	def create
		@order = Order.new
	    @order.order_date= Date.today
	    @order.order_number = "GSSS-IS-#{Random.rand(1000..5000)}"
	    @order.user_id = current_user.id 
	    @order.total = current_user.line_items.sum(:price)
	    @order.confirmation = true
	    @order.save

	    line_items = current_user.line_items
	    line_items.each do |li|
	     oli = OrderLineItem.new
	     oli.order_id = @order.id 
	     oli.product_id = li.product_id
	     oli.price = li.price
	     oli.quantity = li.quantity
	     oli.save
	     end
	     current_user.line_items.delete_all
	     redirect_to "/orders", notice: "Order has been successfully created"
	     end	
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  before_action :check_is_admin, except: [:index, :show]
  def index
  @products=Product.order('price DESC')
  end
  def new
   	@product=Product.new
end
def create
	 @product=Product.new(params[:product].permit(:name, :price, :description, :category_id))
	 if @product.save
	 	redirect_to "/products",notice: "successfully created category"
	 else
	 	render action: "new"
	 	
end
end
def show
	  @product = Product.find(params[:id])
	  @products = Product.all
	  end
	  def edit
	  @product = Product.find(params[:id])
	end

def update
	 @product = Product.find(params[:id])
	 if @product.update_attributes(params[:product].permit(:name, :price, :description))
	 	redirect_to "/products", notice:"successfully updated the product"
	 else
	 	render action: "edit"
end
end
def destroy
	 @product=Product.find(params[:id])
	 @product.destroy
	 redirect_to "/products",notice: "successfully deleted"
	end

end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
	before_action :authenticate_user!, only: [:create]
	def create
		@review=Review.new(params[:review].permit(:rating, :body, :product_id))
		@review.user_id=current_user.id
        if @review.save
      
      redirect_to :back, notice: "successfully added review"
  end
end
def destroy
	 @review=Review.find(params[:id])

	 @review.destroy
	 redirect_to :back,notice: "successfully removed"
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/line_items_helper.rb
module LineItemsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/categories/edit.html.erb
<h2>edit category</h2>
<%= form_for @category do |f| %>
<% if @category.errors.any? %>
<div class="error" style="color: red">
<h3>these errors prohibited to form from begin saved: </h3>
<ul>
<% @category.errors.full_messages.each do |msg| %>
<li> <%= msg %></li>
<% end %>
</ul>
</div>
<% end %>
<%= f.label :name %><br/>
<%=f.text_field :name %><br/>
<%= f.submit %>
<% end %>
<%= link_to "List categories", "/categories" %>

app/views/categories/index.html.erb
<div class="row">
    <div class="col-md-12">
            <div class="page-header">
                <h2>Listing Categories <small>Total : <%= Category.count %> </small></h2>
            </div>
    </div>
</div>

<div class="row">
    <div class="col-md-8">
        <table class="table table-striped">
            <thead>
                <tr>
                    <th>SL NO</th>
                    <th>Name</th>
                </tr>
            </thead>

            <tbody>
                <% count = 1 %>
                <% @categories.each do |category| %>    
                    <tr>
                        <td><%= count %></td>
                        <td><%= category.name %></td>
                    </tr>
                <% count += 1 %>
                <% end %>
            </tbody>    
        </table>
    </div>

    <div class="col-md-4">

    </div>

</div>


<% if user_signed_in? && current_user.is_admin %>
    <%= link_to "New Category", "/categories/new", class:"btn btn-primary" %>
<% end %>


<h2>Listing Categories </h2>
<p> total categories :<%= Category.count %></p>
<ul>
<p><% @categories.each do |category| %></p>
    <li><%= link_to category.name, category %></li>
   <% end %>
</ul> 
<% if  user_signed_in? && current_user.is_admin %>   
<%= link_to "New Category", "/categories/new" %>
<% end %>

app/views/categories/new.html.erb
	<div class="row">
	<div class="col-md-7">
		<h2>Add category</h2>
		<%= form_for @category do |f| %>
		<% if @category.errors.any? %>
		<div class="alert alert-danger">
		<h3>these errors prohibited to form from begin saved: </h3>
		<ul>
		<% @category.errors.full_messages.each do |msg| %>
		<li> <%= msg %></li>
		<% end %>
		</ul>
		</div>
		<% end %>
		<div class="form-group">
		<%= f.label :name %><br/>
		<%=f.text_field :name,class: "form-control" %><br/>
		</div>
		<%= f.submit "Submit", class: "btn btn-primary" %>
		<% end %>
	</div>
	<div class="col-md-5">
	</div>
	</div>
<%= link_to "List categories", "/categories", class:"btn btn-default" %>

app/views/categories/show.html.erb
<h2><%= @category.name %></h2>
<p> there are totally <%= @products.length %> products.</p>

<ul>
   <% @products.each do |product| %>
   	<li><%= product.name %> - <%=product.price %></li>
   	<% end %>
   	</ul>
   	<% if user_signed_in? && current_user.is_admin %>
   	<small><%= link_to "edit", "/categories/#{@category.id}/edit" %>
    </small> | 
    <%= link_to "destroy", @category, data: {method: :delete,confirm: "are you sure"} %> <br/>
    <% end %>
   	<%= link_to "List categories", "/categories" %>

app/views/layouts/_nav.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">ECOMM</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
       
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Categories <span class="caret"></span></a>
          <ul class="dropdown-menu">
              <% Category.all.each do |category| %>
                <li><%= link_to category.name, "/categories/#{category.id}" %>
                </li>
            <% end %>
          </ul>
        </li>

        <li>
        <a href="/products">Products
                <span class="badge"><%= Product.count %></span>
        </a>

        </li> 

      </ul>
      <form class="navbar-form navbar-left">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search">
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
      </form>
      <ul class="nav navbar-nav navbar-right">
            
            <% if user_signed_in? %>
                <li>
            <%= link_to "/line_items" do %>
                        <i class="glyphicon glyphicon-shopping-cart"></i> 
                        <%= current_user.line_items.size %>
            <% end %>
        </li>

        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"> <i class="glyphicon glyphicon-user"></i> <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><%= link_to "Your Orders", "/orders" %></li>
            <li><%= link_to "Account Settings", edit_user_registration_path %></li>
            <li><%= link_to "Logout", destroy_user_session_path, method: :delete %></li>
          </ul>
        </li>

        <% else %>
                    <li><%= link_to "Sign In", new_user_session_path %></li> <li><%= link_to "Register", new_user_registration_path %></li>
        <% end %>

      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Ecomm</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <script src="/js/responsiveslides.min.js"></script>
   <script>
    $(function () {
      $("#slider").responsiveSlides({
      	auto: true,
      	speed: 500,
        namespace: "callbacks",
        pager: true,
      });
    });
  </script>

<script>
// Can also be used with $(document).ready()
$(window).load(function() {
  $('.flexslider').flexslider({
    animation: "slide",
    controlNav: "thumbnails"
  });
});
</script>


	<!---//pop-up-box---->
	 <script>
		$(document).ready(function() {
		$('.popup-with-zoom-anim').magnificPopup({
			type: 'inline',
			fixedContentPos: false,
			fixedBgPos: true,
			overflowY: 'auto',
			closeBtnInside: true,
			preloader: false,
			midClick: true,
			removalDelay: 300,
			mainClass: 'my-mfp-zoom-in'
		});
																		
		});
</script>	

  <%= csrf_meta_tags %>
</head>
<body>

<div class="container">
	<%= render '/layouts/nav' %>
	<% if notice %>
		<div class="alert alert-success">
		  <%= notice %>
		</div>
	<% end %>

	<%= alert %>

	<%= yield %>
	<!---->		

<hr>
	<!--footer-->
<div class="footer">
	<div class="footer-bottom">
		<div class="container">
				<div class="col-md-4 footer-bottom-cate">
					<h6>Top Categories</h6>
					<ul>
						<% Category.limit(5).each do |category| %>
							<li><%= link_to category.name, category %></li>
						<% end %>
					</ul>
				</div>
				<div class="col-md-4 footer-bottom-cate">
					<h6>Feature Projects</h6>
					<ul>
						<% Product.limit(5).each do |product| %>
							<li><%= link_to product.name, product %></li>
						<% end %>
					</ul>
				</div>
				
				<div class="col-md-4 footer-bottom-cate cate-bottom">
					<h6>Our Address</h6>
					<ul>
						<li>Aliquam metus  dui. </li>
						<li>orci, ornareidquet</li>
						<li> ut,DUI.</li>
						<li>nisi, dignissim</li>
						<li class="phone">PH : 6985792466</li>
					</ul>
				</div>
				<div class="clearfix"> </div>
				<p class="footer-class"> © 2016 DCT Academy / GSSSITEW. All Rights Reserved  </p>
			</div>
	</div>
</div>
	
</div>

</body>
</html>

app/views/line_items/index.html.erb
<h2> Your cart items </h2>
<% if @line_items.empty? %>
   <b> Your cart is empty. <%= link_to "shop now", products_path %>
   <% else %>
<table>
    <thead>
<tr>
<th>SL NO</th>
<th>Name</th>
<th>Price</th>
<th>quantity</th>
</tr>
    </thead>
<tbody>
<% count = 1 %>
<% @line_items.each do |line_item| %>
<tr>
<td><%= count %></td>
<td><%= line_item.product.name %></td>
<td><%= line_item.price %></td>
td><%= line_item.product.description %>
<td><%= line_item.quantity %></td>
<td><%= link_to line_item, method: :delete, data: {confirm: "You would want to remove this product from cart? "} do %>
<i class="glyphicon glyphicon-trash"></i>
<i class="glyphicon glyphicon-asterisk"></i>
<% end %>
</td>
</tr>
<% count +=1 %>
<% end %>
</tbody>
</table>
<b> Total : <%= @line_items.sum(:price) %>
<%= form_for Order.new do |f| %>
<%= f.submit "Checkout",class: "btn btn-lg btn-warning" %>
<% end %>
<% end %>

app/views/orders/index.html.erb
<div class="row">
    <div class="page-header">
        <h2>Your Orders</h2>
    </div>

</div>

<div class="panel-group" id="accordion" role="tablist" aria-multiselectable="true">


    <% @orders.each do |order| %>
  <div class="panel panel-default">
    <div class="panel-heading" role="tab" id="headingOne">
      <h4 class="panel-title">
        <a role="button" data-toggle="collapse" data-parent="#accordion" href="#order_<%= order.id %>" aria-expanded="true" aria-controls="collapseOne">
          <span class="pull-left"><%= order.order_number %></span>
          <span class="pull-right"><%= order.order_date.strftime("%A, %d %B %Y ") %></span>
          <br/>
        </a>
      </h4>
    </div>

    <div id="order_<%= order.id %>" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingOne">
      <div class="panel-body">
       <table class="table">
                    <thead>
                            <tr>
                                <th>Name</th>
                                <th>Description</th>
                                <th>Category</th>
                                <th>Price</th>


                            </tr>
                    </thead>

                    <tbody>
                            <% order.order_line_items.each do |line_item| %>
                                <tr>
                                    <td><%= link_to line_item.product.name,"/products/#{line_item.product.id}" %>
                                    </td>

                                     <td><%= line_item.product.description %></td>
                                     <td><%= line_item.product.category.name %></td>
                                    <td><%= line_item.price %></td>

                                </tr>
                            <% end %>
                    </tbody>
       </table>

       <b>Total : INR <%= order.order_line_items.sum(:price) %></b>
      </div>
    </div>
  </div>
  <% end %>
</div>

app/views/products/_banner.html.erb
<!--banner-->
<div class="banner">
	<div class="col-sm-3 banner-mat">
		<img class="img-responsive"	src="/images/ba1.jpg" alt="">
	</div>
	<div class="col-sm-6 matter-banner">
	 	<div class="slider">
	    	<div class="callbacks_container">
	      		<ul class="rslides" id="slider">
	        		<li>
	          			<img src="/images/1.jpg" alt="">
	       			 </li>
			 		 <li>
	          			<img src="/images/2.jpg" alt="">   
	       			 </li>
					 <li>
	          			<img src="/images/1.jpg" alt="">
	        		</li>	
	      		</ul>
	 	 	</div>
		</div>
	</div>
	<div class="col-sm-3 banner-mat">
		<img class="img-responsive" src="/images/ba.jpg" alt="">
	</div>
	<div class="clearfix"> </div>
</div>
<!--//banner-->

app/views/products/_content.html.erb
<!--content-->
<div class="content">
	<div class="container">
		<div class="content-top">
			<div class="content-top1">
			
			<% Product.all.each do |product| %>		
			<div class="col-md-3 col-md2">
					<div class="col-md1 simpleCart_shelfItem">
						<a href="/products/<%= product.id %>">
							<img class="img-responsive" src="/images/pi2.png" alt="" />
						</a>
						<h3><a href="/products/<%= product.id %>"><%= product.name %></a></h3>
						<div class="price">
								<h5 class="item_price">INR <%= product.price %></h5>
								<a href="/line_items/add?product_id=<%= product.id %>" class="btn btn-warning">Add To Cart</a>
								<div class="clearfix"> </div>
						</div>
						
					</div>
				</div>	
			<% end %>
						
					</div>
				</div>	
			<div class="clearfix"> </div>
			</div>	
		</div>
	</div>
</div>
<!--//content-->

app/views/products/_product_details.html.erb
<div class="single">

<div class="container">
<div class="col-md-12">
	<div class="col-md-5 grid">		
		<div class="flexslider">
			  <ul class="slides">
			    <li data-thumb="/images/si.jpg">
			        <div class="thumb-image"> <img src="/images/si.jpg" data-imagezoom="true" class="img-responsive"> </div>
			    </li>
			    <li data-thumb="/images/si1.jpg">
			         <div class="thumb-image"> <img src="/images/si1.jpg" data-imagezoom="true" class="img-responsive"> </div>
			    </li>
			    <li data-thumb="/images/si2.jpg">
			       <div class="thumb-image"> <img src="/images/si2.jpg" data-imagezoom="true" class="img-responsive"> </div>
			    </li> 
			  </ul>
		</div>
	</div>	
<div class="col-md-7 single-top-in">
						<div class="single-para simpleCart_shelfItem">
							<h1><%= @product.name %></h1>
							<p><%= @product.description %></p>
							<div class="star-on">
								
								<div class="review">
									<a href="#"> <%= @product.reviews.size %> </a>/
									<a href="#">  Write a review</a>
								</div>
							<div class="clearfix"> </div>
							</div>
							
								<label  class="add-to item_price">INR <%= @product.price %></label>
							
							<div class="available">
								<h6>Available Options :</h6>
								<ul>
									
								Size : <select>
									<option>Large</option>
									<option>Medium</option>
									<option>small</option>

								</select>
								
							</ul>
						</div>
						</div>
					</div>


<% if user_signed_in? %>
	
	<%= link_to  "/line_items/add?product_id=#{@product.id}", class: "btn btn-info pull-right" do %>
		 <i class="glyphicon glyphicon-plus"></i> Add to cart
	<% end %>


<% else %>
	<p>Login to add to cart</p>
<% end %>

<% if user_signed_in? && current_user.is_admin %>
	<%= link_to "edit", "/products/#{@product.id}/edit" %>
<% end %>

			<div class="clearfix"> </div>
			<div class="content-top1">
				

			<% Product.order("RANDOM()").limit(3).each do |product| %>	
			<div class="col-md-4 col-md3">
					<div class="col-md1 simpleCart_shelfItem">
						<a href="/products/<%= product.id %>">
							<img class="img-responsive" src="/images/pi7.png" alt="" />
						</a>
						<h3><a href="<%= product.id %>"><%= product.name %></a></h3>
						<div class="price">
								<h5 class="item_price">INR <%= product.price %></h5>
								<a href="/line_items/add?product_id=<%= product.id %>"">Add To Cart</a>
								<div class="clearfix"> </div>
						</div>
						
					</div>
				</div>	
			<% end %>
			
			<div class="clearfix"> </div>
			</div>		
</div>

				
		

app/views/products/edit.html.erb
h2>Add Product</h2>
<%= form_for @product do |f| %>

<% if @product.errors.any? %>
<div class="error" style="color: red">
<h3>These errors prohibited the form from being saved:</h3>
<ul>
<% @product.errors.full_messages.each do |msg| %>
<li><%= msg %></li>
<% end %>
</ul>
</div>
<% end %>

<%= f.label :name%><br/>
<%= f.text_field :name %><br/>

<%= f.label :price%><br/>
<%= f.text_field :price%><br/>

<%= f.label :description%><br/>
<%= f.text_area :description %><br/>
<%= f.label :category_id%><br/>

<%= f.collection_select :category_id, Category.all, :id, :name, prompt: "select Category"%>

<%= f.submit %>
<% end %>
<%= link_to "List products","/products"%>

app/views/products/index.html.erb
<%=render '/products/banner' %>

<h1>listing products</h1>
<p>Total Products : <%= @products.size %></p>
<%=render '/products/content' %>

<% if  user_signed_in? && current_user.is_admin %>
<%= link_to "add products",new_product_path %>
<% end %>

app/views/products/new.html.erb

<%notice%>

<h2>Add Product</h2>
<%= form_for @product do |f| %>

<% if @product.errors.any? %>
<div class="error" style="color: red">
<h3>These errors prohibited the form from being saved:</h3>
<ul>
<% @product.errors.full_messages.each do |msg| %>
<li><%= msg %></li>
<% end %>
</ul>
</div>
<% end %>

<%= f.label :name%><br/>
<%= f.text_field :name %><br/>

<%= f.label :price%><br/>
<%= f.text_field :price%><br/>

<%= f.label :description%><br/>
<%= f.text_area :description %><br/>
<%= f.label :category_id%><br/>

<%= f.collection_select :category_id, Category.all, :id, :name, prompt: "select Category"%>
<%= f.submit "Create",class: "btn btn-lg btn-primary" %>
<% end %>

<%= link_to "List products","/products"%>

app/views/products/show.html.erb
<h3><%= @product.name %></h3>
<ul>
INR <%= @product.price %>
<p><%=@product.description%></p>

<% if user_signed_in? %>
<%= link_to "/line_items/add?product_id=#{@product.id}", class: "btn btn-info" do %>
<i class= "glyphicon glyphicon-plus"></i>Add to cart
<% end %>

<% else %>
<p> Login to add to cart</p>
<% end %>
</ul>


<% if user_signed_in? && current_user.is_admin %>
<small><%= link_to "edit", "/products/#{@product.id}/edit"%>| 
<%= link_to "destroy", @product, data: { method: :delete, confirm:"Are you sure you want to delete"}%></small> <br>
<% end %>
<%= link_to "List Products","/products"%>

<h3> Reviews</h3>
<ul>
<% @product.reviews.each do |review| %>
<li><%= review.rating %> - <%= review.body %> by <%= review.user.email %> | 
<% if user_signed_in? && (review.user_id==current_user.id || current_user.is_admin) %>
<%= link_to "Remove",review, method: :delete,data: {confirm: "ru sure to remove"} %>
<% end %>
<% end %>
</li>
</ul>




<h3> Add Review</h3>
<%= form_for Review.new do |f| %>
<label><Rating></label>
<%= f.radio_button :rating, 1 %> 1
<%= f.radio_button :rating, 2 %> 2
<%= f.radio_button :rating, 3 %> 3
<%= f.radio_button :rating, 4 %> 4
<%= f.radio_button :rating, 5 %> 5
<br/>
<%= f.hidden_field :product_id, value: @product.id %>
<label> Body </label>
<%= f.text_area :body %>

<br/>
<%= f.submit %>
<% end %>